/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package medical_store;

import com.mysql.jdbc.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.SQLIntegrityConstraintViolationException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;


/**
 *
 * @author dell
 */
public class Manage_Stocks extends javax.swing.JFrame {

    /**
     * Creates new form Manage_Stocks
     */
    public Manage_Stocks() {
        initComponents();
        jTable_stock_table.getColumn("Medicine Name").setPreferredWidth(150);
        jTable_stock_table.getColumn("Supplier Name").setPreferredWidth(150);
        jTable_stock_table.getColumn("Quantity Purchase").setPreferredWidth(120);
        jTable_stock_table.getColumn("Cost of Purchase").setPreferredWidth(120);
        jTable_stock_table.getColumn("Date of Purchase").setPreferredWidth(120);
        jTable_stock_items.getColumn("Sr. No.").setPreferredWidth(60);
        jTable_stock_items.getColumn("Medicine Name").setPreferredWidth(150);
        jTable_stock_items.getColumn("Supplier Name").setPreferredWidth(120);
        jTable_stock_items.getColumn("Quantity Purchased").setPreferredWidth(120);
        jTable_stock_items.getColumn("Cost of Purchase").setPreferredWidth(120);
        jTable_stock_items.getColumn("Date of Purchase").setPreferredWidth(120);
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
        jXDatePicker1.setFormats(dateFormat);
        Date date = new Date();
        jLabel_date_of_purchase.setText(dateFormat.format(date));
        try(Connection conn = MySQL_Connector.getConnection()) {
            String query1 = "select supplier_name from supplier";
            ResultSet rs1 = MySQL_Connector.runQuery(conn, query1);
            while(rs1.next()) {
                jComboBox_supplier_name.addItem(rs1.getString("supplier_name"));
                jComboBox2_supplier_name.addItem(rs1.getString("supplier_name"));
            }
            
            String query2 = "select medc_name from medicine";
            ResultSet rs2 = MySQL_Connector.runQuery(conn, query2);
            while(rs2.next()) {
                jComboBox_medicine_name.addItem(rs2.getString("medc_name"));
                jComboBox1_medicine_name.addItem(rs2.getString("medc_name"));
                jComboBox2_medicine_name.addItem(rs2.getString("medc_name"));

            }
            conn.close();
            rs1.close();
            rs2.close();
        }catch(SQLException e) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, e); 
        }
        jComboBox_supplier_name.setSelectedIndex(-1);
        jComboBox_medicine_name.setSelectedIndex(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox_supplier_name = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jComboBox_medicine_name = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jXDatePicker = new org.jdesktop.swingx.JXDatePicker();
        jButton_search = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_stock_table = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_stock_info = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jComboBox2_medicine_name = new javax.swing.JComboBox<>();
        jComboBox2_supplier_name = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        jLabel12 = new javax.swing.JLabel();
        jTextField_quantity_purchased = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField_total_cost = new javax.swing.JTextField();
        jButton_update_stock = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable_stock_info1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1_medicine_name = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel_date_of_purchase = new javax.swing.JLabel();
        jButton_add_item = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_stock_items = new javax.swing.JTable();
        jButton_add_to_database = new javax.swing.JButton();
        jLabel_quantity_purchased = new javax.swing.JTextField();
        jLabel_cost_of_purchase = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        generate_bill_button = new javax.swing.JButton();
        manage_medicine_button = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        manage_employees_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Search"));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setText("Supplier Name:");

        jComboBox_supplier_name.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_supplier_nameItemStateChanged(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel2.setText("Medicine Name:");

        jComboBox_medicine_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_medicine_nameActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel3.setText("Date of Purchase:");

        jXDatePicker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXDatePickerActionPerformed(evt);
            }
        });

        jButton_search.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jButton_search.setText("Search");
        jButton_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_searchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(26, 26, 26))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_search, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_supplier_name, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_medicine_name, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox_medicine_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_supplier_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(38, 38, 38)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jXDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jButton_search)
                .addGap(25, 25, 25))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Matching Entries"));

        jTable_stock_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Medicine Name", "Supplier Name", "Quantity Purchase", "Cost of Purchase", "Date of Purchase"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_stock_table.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(jTable_stock_table);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(148, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Stock Information"));

        jTable_stock_info.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Medicine ID", null},
                {"Medicine Name", null},
                {"Supplier Name", null},
                {"Date of Purchase", null},
                {"Quantity Purchased (in strips)", null},
                {"Current Available Quantity ", null},
                {"Cost of Purchase", null}
            },
            new String [] {
                "Term", "Details"
            }
        ));
        jScrollPane2.setViewportView(jTable_stock_info);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("View Older Stocks", jPanel1);

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Update Information"));

        jLabel9.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel9.setText("Medicine Name:");

        jLabel10.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel10.setText("Supplier Name:");

        jComboBox2_medicine_name.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2_medicine_nameItemStateChanged(evt);
            }
        });
        jComboBox2_medicine_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2_medicine_nameActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel11.setText("Purchase Date:");

        jXDatePicker1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXDatePicker1ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel12.setText("Quantity Purchased:");

        jTextField_quantity_purchased.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_quantity_purchasedActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel13.setText("Total Cost of Purchase:");

        jTextField_total_cost.setEditable(false);

        jButton_update_stock.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jButton_update_stock.setText("Update Stock");
        jButton_update_stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_update_stockActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBox2_supplier_name, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel9Layout.createSequentialGroup()
                                    .addComponent(jXDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(29, 29, 29)
                                    .addComponent(jLabel13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextField_total_cost, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel9Layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel9Layout.createSequentialGroup()
                                            .addGap(116, 116, 116)
                                            .addComponent(jLabel12)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextField_quantity_purchased, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel9Layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jComboBox2_medicine_name, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel7))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(393, 393, 393)
                        .addComponent(jButton_update_stock, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2_medicine_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(61, 61, 61)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jComboBox2_supplier_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jTextField_quantity_purchased, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jXDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jTextField_total_cost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(jButton_update_stock)
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Update Stock", jPanel3);

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Delete Information"));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 445, Short.MAX_VALUE)
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("Stock Information"));

        jTable_stock_info1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Medicine ID", null},
                {"Medicine Name", null},
                {"Supplier Name", null},
                {"Date of Purchase", null},
                {"Quantity Purchased (in strips)", null},
                {"Current Available Quantity ", null},
                {"Cost of Purchase", null}
            },
            new String [] {
                "Term", "Details"
            }
        ));
        jScrollPane4.setViewportView(jTable_stock_info1);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                .addGap(176, 176, 176))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(34, 34, 34))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(320, 320, 320)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Delete Stock", jPanel4);

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel4.setText("Medicine Name:");

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel5.setText("Date of Purchase:");

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel6.setText("Quantity of Strips Purchased:");

        jLabel8.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel8.setText("Total Cost of Purchase:");

        jLabel_date_of_purchase.setEnabled(false);
        jLabel_date_of_purchase.setOpaque(true);

        jButton_add_item.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jButton_add_item.setLabel("Add item to Stock");
        jButton_add_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_add_itemActionPerformed(evt);
            }
        });

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Stock Items"));

        jTable_stock_items.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sr. No.", "Medicine Name", "Supplier Name", "Quantity Purchased", "Cost of Purchase", "Date of Purchase"
            }
        ));
        jScrollPane3.setViewportView(jTable_stock_items);

        jButton_add_to_database.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jButton_add_to_database.setText("Add Stock to Database");
        jButton_add_to_database.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_add_to_databaseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_add_to_database, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_add_to_database)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jLabel_quantity_purchased.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLabel_quantity_purchasedActionPerformed(evt);
            }
        });

        jLabel_cost_of_purchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLabel_cost_of_purchaseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel_date_of_purchase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(42, 42, 42)
                                        .addComponent(jLabel_cost_of_purchase))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel_quantity_purchased))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(jComboBox1_medicine_name, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_add_item, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117)))
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jComboBox1_medicine_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel_date_of_purchase, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel_quantity_purchased, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel_cost_of_purchase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61)
                        .addComponent(jButton_add_item))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Insert New Stock", jPanel2);

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder("Navigation"));

        generate_bill_button.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        generate_bill_button.setText("Generate Bill");
        generate_bill_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generate_bill_buttonActionPerformed(evt);
            }
        });

        manage_medicine_button.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        manage_medicine_button.setText("Manage Medicines");
        manage_medicine_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manage_medicine_buttonActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(201, 45, 45));
        jButton6.setText("Manage Stocks");

        manage_employees_button.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        manage_employees_button.setText("Manage Employees");
        manage_employees_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manage_employees_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(manage_medicine_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(generate_bill_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manage_employees_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(generate_bill_button)
                .addGap(34, 34, 34)
                .addComponent(manage_medicine_button)
                .addGap(35, 35, 35)
                .addComponent(jButton6)
                .addGap(34, 34, 34)
                .addComponent(manage_employees_button)
                .addContainerGap(223, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1030, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_searchActionPerformed
        String supplier_name = null;
        String medicine_name = null;
        String Date = null;
        
        if(jComboBox_supplier_name.getSelectedIndex() != -1) {
            supplier_name = jComboBox_supplier_name.getSelectedItem().toString();
        }
        
        if(jComboBox_medicine_name.getSelectedIndex() != -1) {
           medicine_name = jComboBox_medicine_name.getSelectedItem().toString();
        }
        if(jXDatePicker.getDate() != null) {
            SimpleDateFormat sysdate = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
            Date = sysdate.format(jXDatePicker.getDate()).toString();
        }
        
        try(Connection conn = MySQL_Connector.getConnection()) {
            if(supplier_name != null && medicine_name == null && Date == null) {
                String query1 = "select supplier_id from supplier where supplier_name = '"+supplier_name+"'";
                ResultSet rs1 = MySQL_Connector.runQuery(conn, query1);
                Integer supplier_id = 0;
                if(rs1.next()) {
                    supplier_id = Integer.parseInt(rs1.getString("supplier_id"));
                }
                String medicine_id = null;
                DefaultTableModel model = (DefaultTableModel)this.jTable_stock_table.getModel();
                String query3 = "select * from stock_details where supplier_id = '"+supplier_id+"' order by purchase_date_timestamp desc";
                ResultSet rs3 = MySQL_Connector.runQuery(conn, query3);
                while(rs3.next()) {
                    medicine_id = rs3.getString("medc_id");
                    String query4 = "select medc_name from medicine where medc_id = '"+medicine_id+"'";
                    ResultSet rs4 = MySQL_Connector.runQuery(conn, query4);
                    if(rs4.next())
                        medicine_name = rs4.getString("medc_name");
                    model.addRow(new Object[]{medicine_name, supplier_name, rs3.getString("quantity"), rs3.getString("total_cost_of_purchase"), rs3.getString("purchase_date_timestamp")});    
                }
                tableSort();
                
            }else if(supplier_name != null && Date != null && medicine_name == null) {
                String query1 = "select supplier_id from supplier where supplier_name = '"+supplier_name+"'";
                ResultSet rs1 = MySQL_Connector.runQuery(conn, query1);
                Integer supplier_id = 0;
                if(rs1.next()) {
                    supplier_id = Integer.parseInt(rs1.getString("supplier_id"));
                }
                DefaultTableModel model = (DefaultTableModel)this.jTable_stock_table.getModel();
                String query2 = "select * from stock_details where supplier_id = '"+supplier_id+"' && purchase_date_timestamp = '"+Date+"'";
                ResultSet rs2 = MySQL_Connector.runQuery(conn, query2);
                String medicine_id = null;
                while(rs2.next()) {
                    medicine_id = rs2.getString("medc_id");
                    String query4 = "select medc_name from medicine where medc_id = '"+medicine_id+"'";
                    ResultSet rs4 = MySQL_Connector.runQuery(conn, query4);
                    if(rs4.next())
                        medicine_name = rs4.getString("medc_name");
                    model.addRow(new Object[]{medicine_name, supplier_name, rs2.getString("quantity"), rs2.getString("total_cost_of_purchase"), rs2.getString("purchase_date_timestamp")});
                }
                tableSort();
            }else if(supplier_name == null && medicine_name != null && Date == null) {
                String query1 = "select medc_id from medicine where medc_name = '"+medicine_name+"'";
                ResultSet rs1 = MySQL_Connector.runQuery(conn, query1);
                DefaultTableModel model = (DefaultTableModel)this.jTable_stock_table.getModel();
                String medicine_id = null;
                if(rs1.next()) {
                    medicine_id = rs1.getString("medc_id");
                }
                String query2 = "select * from stock_details where medc_id = '"+medicine_id+"' order by purchase_date_timestamp";
                ResultSet rs2 = MySQL_Connector.runQuery(conn, query2);
                while(rs2.next()) {
                    String query3 = "select supplier_name from supplier where supplier_id = '"+Integer.parseInt(rs2.getString("supplier_id"))+"'";
                    ResultSet rs3 = MySQL_Connector.runQuery(conn, query3);
                    if(rs3.next())
                        supplier_name = rs3.getString("supplier_name");
                    model.addRow(new Object[]{medicine_name, supplier_name, rs2.getString("quantity"), rs2.getString("total_cost_of_purchase"), rs2.getString("purchase_date_timestamp")});
                }
            }else if(supplier_name != null && medicine_name != null && Date != null){
                DefaultTableModel model = (DefaultTableModel)this.jTable_stock_table.getModel();
                String query1 = "select * from stock_details where medc_id = (select medc_id from medicine where medc_name = '"+medicine_name+"') && purchase_date_timestamp = '"+Date+"'";
                ResultSet rs1 = MySQL_Connector.runQuery(conn, query1);
                if(rs1.next()) {
                    model.addRow(new Object[]{medicine_name, supplier_name, rs1.getString("quantity"), rs1.getString("total_cost_of_purchase"), rs1.getString("purchase_date_timestamp")});
                }
            }
            conn.close();
        }catch(SQLException e) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, e);
        }
        
    }//GEN-LAST:event_jButton_searchActionPerformed

    private static int serial_no = 1;
    
    private void jButton_add_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_add_itemActionPerformed
        String medicine_name = jComboBox1_medicine_name.getSelectedItem().toString();
        String supplier_name = "";
        try(Connection conn = MySQL_Connector.getConnection()) {
            String query1 = "select supplier_name from supplier where supplier_id = (select supplier_id from medicine where medc_name = '"+medicine_name+"')";
            ResultSet rs1 = MySQL_Connector.runQuery(conn, query1);
            if(rs1.next())
             supplier_name = rs1.getString("supplier_name");
            conn.close();
        }catch(SQLException e) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, e);
        }
        String Date = jLabel_date_of_purchase.getText();
        Integer cost = Integer.parseInt(jLabel_cost_of_purchase.getText());
        Integer quantity = Integer.parseInt(jLabel_quantity_purchased.getText());
        DefaultTableModel model = (DefaultTableModel)this.jTable_stock_items.getModel();
        model.addRow(new Object[] {serial_no, medicine_name, supplier_name, quantity, cost, Date});
        serial_no++;
    }//GEN-LAST:event_jButton_add_itemActionPerformed

    private void jLabel_cost_of_purchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLabel_cost_of_purchaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_cost_of_purchaseActionPerformed

    private void jLabel_quantity_purchasedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLabel_quantity_purchasedActionPerformed
        String quantity = jLabel_quantity_purchased.getText();
        String medicine_name = jComboBox1_medicine_name.getSelectedItem().toString();
        float cost = 0; 
        Integer cost1;
        try(Connection conn = MySQL_Connector.getConnection()) {
            String query1 = "select medc_cost_per_strip from medicine where medc_name = '"+medicine_name+"'";
            ResultSet rs1 = MySQL_Connector.runQuery(conn, query1);
            if(rs1.next())
                cost = Float.parseFloat(rs1.getString("medc_cost_per_strip")) * Float.parseFloat(quantity);
            cost1 = (int)Math.ceil(cost);
            jLabel_cost_of_purchase.setText(cost1.toString());
            conn.close();
        }catch(SQLException e) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_jLabel_quantity_purchasedActionPerformed

    private void jButton_add_to_databaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_add_to_databaseActionPerformed
        String medicine_id = null;
        Integer supplier_id = 0;
        Integer quantity = 0;
        Integer cost;
        Integer tablets_in_strips;
        String purchase_date = null;
        try(Connection conn = MySQL_Connector.getConnection()) {
            for(int i = 0; i<jTable_stock_items.getRowCount(); i++) {
                String query1 = "select medc_id, medc_per_strip, medc_quantity_in_tablets from medicine where medc_name = '"+jTable_stock_items.getValueAt(i, 1).toString()+"'";
                ResultSet rs1 = MySQL_Connector.runQuery(conn, query1);
                if(rs1.next())
                    medicine_id = rs1.getString("medc_id");
                tablets_in_strips = Integer.parseInt(rs1.getString("medc_quantity_in_tablets")) + (int)Math.ceil(Float.parseFloat(rs1.getString("medc_per_strip")) * (int)Math.ceil(Float.parseFloat(jTable_stock_items.getValueAt(i, 3).toString())));
                String query2 = "select supplier_id from supplier where supplier_name = '"+jTable_stock_items.getValueAt(i, 2).toString()+"'";
                ResultSet rs2 = MySQL_Connector.runQuery(conn, query2);
                if(rs2.next())
                    supplier_id = Integer.parseInt(rs2.getString("supplier_id"));
                purchase_date = jTable_stock_items.getValueAt(i, 5).toString();
                cost = Integer.parseInt(jTable_stock_items.getValueAt(i, 4).toString());
                quantity = Integer.parseInt(jTable_stock_items.getValueAt(i, 3).toString());
                
                String query6 = "select * from stock_details where medc_id = '"+medicine_id+"' && purchase_date_timestamp = '"+purchase_date+"'";
                ResultSet rs6 = MySQL_Connector.runQuery(conn, query6);
                if(rs6.next()) {
                    JOptionPane.showMessageDialog(null, "Entry already exists! Please update stock");
                }else {
                    String query4 = "insert into stock_details values('"+medicine_id+"', '"+supplier_id+"', '"+purchase_date+"', '"+quantity+"', '"+cost+"')";
                    MySQL_Connector.runUpdateQuery(conn, query4);
                    String query5 = "update medicine set medc_quantity_in_tablets = '"+tablets_in_strips+"' where medc_id = '"+medicine_id+"'";
                    MySQL_Connector.runUpdateQuery(conn, query5);
                    JOptionPane.showMessageDialog(null, new String("Entry saved successfully in the Database!"));
                }
            }
            conn.close();
        }catch (SQLException e) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_jButton_add_to_databaseActionPerformed

    private void jButton_update_stockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_update_stockActionPerformed
        String medicine_id = null;
        Integer medicine_quantity = 0;
        Integer total_quantity = Integer.parseInt(jTextField_quantity_purchased.getText());
        System.out.println(total_quantity);
        float total_cost = Float.parseFloat(jTextField_total_cost.getText());
        Integer cost = (int)Math.ceil((double)total_cost);
        SimpleDateFormat sysdate = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss"); 
        String date = sysdate.format(jXDatePicker1.getDate()).toString();
        try(Connection conn = MySQL_Connector.getConnection()) {
           String query1 = "select medc_id, medc_quantity_in_tablets, medc_per_strip from medicine where medc_name = '"+jComboBox2_medicine_name.getSelectedItem().toString()+"'";
           ResultSet rs1 = MySQL_Connector.runQuery(conn, query1);
           if(rs1.next()) {
               medicine_id = rs1.getString("medc_id");
               medicine_quantity = Integer.parseInt(rs1.getString("medc_quantity_in_tablets"));
           }
           String query2 = "update stock_details set quantity = '"+total_quantity+"', total_cost_of_purchase = '"+cost+"' where medc_id = '"+medicine_id+"' && purchase_date_timestamp = '"+date+"'";
           MySQL_Connector.runUpdateQuery(conn, query2);
            String query3 = "update medicine set medc_quantity_in_tablets = '"+Integer.parseInt(rs1.getString("medc_quantity_in_tablets"))+(int)Math.ceil(Float.parseFloat(rs1.getString("medc_per_strip")))*Integer.parseInt(jTextField_quantity_purchased.getText())+"' where medc_name = '"+jComboBox2_medicine_name.getSelectedItem().toString()+"'";
           MySQL_Connector.runUpdateQuery(conn, query3);
           JOptionPane.showMessageDialog(null, "Entry Updated successfully!");
        }catch(SQLException e) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, e);
       }
    }//GEN-LAST:event_jButton_update_stockActionPerformed

    private void jComboBox2_medicine_nameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2_medicine_nameItemStateChanged

    }//GEN-LAST:event_jComboBox2_medicine_nameItemStateChanged

    private void jComboBox2_medicine_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2_medicine_nameActionPerformed
        try(Connection conn = MySQL_Connector.getConnection()) {
            String query1 = "select medc_id from medicine where medc_name = '"+jComboBox2_medicine_name.getSelectedItem().toString()+"'";
            ResultSet rs1 = MySQL_Connector.runQuery(conn, query1);
            if(rs1.next()) {
                String query2 = "select supplier_name from supplier where supplier_id = (select supplier_id from medicine where medc_id = '"+rs1.getString("medc_id")+"')";
                ResultSet rs2 = MySQL_Connector.runQuery(conn, query2);
                if(rs2.next()) {
                    jComboBox2_supplier_name.setSelectedItem(rs2.getString("supplier_name"));
                }
            }
            conn.close();
        }catch(SQLException e) {
             Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_jComboBox2_medicine_nameActionPerformed

    private void jXDatePicker1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXDatePicker1ActionPerformed
        SimpleDateFormat sysdate = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss"); 
        String date = sysdate.format(jXDatePicker1.getDate()).toString();
        try(Connection conn = MySQL_Connector.getConnection()) {
            String query1 = "select medc_id from medicine where medc_name = '"+jComboBox2_medicine_name.getSelectedItem().toString()+"'";
            ResultSet rs1 = MySQL_Connector.runQuery(conn, query1);
            if(rs1.next()) {
                String query2 = "select * from stock_details where medc_id = '"+rs1.getString("medc_id")+"' && purchase_date_timestamp = '"+date+"'";
                ResultSet rs2 = MySQL_Connector.runQuery(conn, query2);
                if(rs2.next()) {
                    jTextField_total_cost.setText(rs2.getString("total_cost_of_purchase"));
                    jTextField_quantity_purchased.setText(rs2.getString("quantity"));
                }
            }
            conn.close();
        }catch(SQLException e) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_jXDatePicker1ActionPerformed

    private void jTextField_quantity_purchasedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_quantity_purchasedActionPerformed
        try(Connection conn = MySQL_Connector.getConnection()) {
            String query1 = "select medc_cost_per_strip from medicine where medc_name = '"+jComboBox2_medicine_name.getSelectedItem().toString()+"'";
            Integer cost  = Integer.parseInt(jTextField_quantity_purchased.getText());
            ResultSet rs1 = MySQL_Connector.runQuery(conn, query1);
            if(rs1.next()) {
                cost = cost * (int)Math.ceil(Float.parseFloat(rs1.getString("medc_cost_per_strip")));
                jTextField_total_cost.setText(cost.toString());
            }
            conn.close();
        }catch(SQLException e) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_jTextField_quantity_purchasedActionPerformed

    private void jXDatePickerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXDatePickerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jXDatePickerActionPerformed

    private void jComboBox_medicine_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_medicine_nameActionPerformed
       
    }//GEN-LAST:event_jComboBox_medicine_nameActionPerformed

    private void jComboBox_supplier_nameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_supplier_nameItemStateChanged
      /*  System.out.println(jComboBox_medicine_name.getSelectedItem().toString());
        try(Connection conn = MySQL_Connector.getConnection()) {
           String query = "select supplier_name from supplier where supplier_id = (select supplier_id from medicine where medc_name = '"+jComboBox_medicine_name.getSelectedItem().toString()+"')";
           ResultSet rs1 = MySQL_Connector.runQuery(conn, query);
           if(rs1.next()) {
               jComboBox_supplier_name.setSelectedItem(rs1.getString("supplier_name"));
           }
           conn.close();
        }catch(SQLException e) {
             Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, e);
        }*/
    }//GEN-LAST:event_jComboBox_supplier_nameItemStateChanged

    private void generate_bill_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generate_bill_buttonActionPerformed
        Owner_Generate_Bill window = new Owner_Generate_Bill();
        window.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_generate_bill_buttonActionPerformed

    private void manage_medicine_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manage_medicine_buttonActionPerformed
        this.setVisible(false);
        Owner_Manage_Medicine window = new Owner_Manage_Medicine();
        window.setVisible(true);
    }//GEN-LAST:event_manage_medicine_buttonActionPerformed

    private void manage_employees_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manage_employees_buttonActionPerformed
        this.setVisible(false);
        Owner_Manage_Employee window = new Owner_Manage_Employee();
        window.setVisible(true);
    }//GEN-LAST:event_manage_employees_buttonActionPerformed
    
    private void tableSort() {
        TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(jTable_stock_table.getModel());
        jTable_stock_table.setRowSorter(sorter);

        List<RowSorter.SortKey> sortKeys = new ArrayList<>(25);
        sortKeys.add(new RowSorter.SortKey(4, SortOrder.DESCENDING));
        sorter.setSortKeys(sortKeys);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manage_Stocks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manage_Stocks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manage_Stocks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manage_Stocks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manage_Stocks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton generate_bill_button;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton_add_item;
    private javax.swing.JButton jButton_add_to_database;
    private javax.swing.JButton jButton_search;
    private javax.swing.JButton jButton_update_stock;
    private javax.swing.JComboBox<String> jComboBox1_medicine_name;
    private javax.swing.JComboBox<String> jComboBox2_medicine_name;
    private javax.swing.JComboBox<String> jComboBox2_supplier_name;
    private javax.swing.JComboBox<String> jComboBox_medicine_name;
    private javax.swing.JComboBox<String> jComboBox_supplier_name;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jLabel_cost_of_purchase;
    private javax.swing.JLabel jLabel_date_of_purchase;
    private javax.swing.JTextField jLabel_quantity_purchased;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable_stock_info;
    private javax.swing.JTable jTable_stock_info1;
    private javax.swing.JTable jTable_stock_items;
    private javax.swing.JTable jTable_stock_table;
    private javax.swing.JTextField jTextField_quantity_purchased;
    private javax.swing.JTextField jTextField_total_cost;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    private javax.swing.JButton manage_employees_button;
    private javax.swing.JButton manage_medicine_button;
    // End of variables declaration//GEN-END:variables
}
